# Generated by Django 6.0.3 on 2026-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="duration_interval",
            field=models.DurationField(verbose_name="Время на выполнение", null=True),
        ),
        migrations.RunSQL(
            "UPDATE habits_habit SET duration_interval = duration * '1 second'::interval;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveField(
            model_name="habit",
            name="duration",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="duration_interval",
            new_name="duration",
        ),
    ]
